### ISSUE TITLE
Move to IPLD organization

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-ipld#25]
Should this be moved?

**Comment by parkan** [comment]
:+1:

**Comment by daviddias** [comment]
yes please

**Comment by RichardLitt** [comment]
@whyrusleeping Anything I should consider when moving it? Or do you want to?

**Comment by daviddias** [comment]
@RichardLitt it is go, every import path needs to get updated along the way

**Comment by ghost** [comment]
Yeah it's delicate, just moving the repo is only 10% of the job

**Comment by chrisdostert** [comment]
@whyrusleeping @RichardLitt @diasdavid could do this in multiple steps; docker/docker had the same situation when moving to moby/moby (which is still in transit). Github will transparently redirect requests for github.com/ipfs/go-ipld to github.com/ipld/go-ipld if the repo is transferred to that org for example

**Comment by daviddias** [comment]
Pretty please 🙏🏽
