### ISSUE TITLE
rebase on go-multicodec

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipld#3]
https://github.com/jbenet/go-multicodec is ready. we need to pull it in and rebase go-ipld on top of it. We should basically remove https://github.com/ipfs/go-ipld/tree/master/coding.

Tricky parts:
- [x] ugorji codec allowed us to specify the map type to use when decoding. looks like the new decoders do not. not sure what we can do about that without walking the whole datastructure and converting everything.
- [x]  make sure decoding different wire types (cbor, json) to the same object works ok.
- [x] make a package for marshaling + hashing (multihash) an ipld object. (maybe coding pkg can turn into this?)

**Comment by mildred** [comment]
Has this been implemented in PR #6, is there something left to do ? If all is covered, I'd suggest closing this issue.

**Comment by jbenet** [comment]
thanks @mildred
