### ISSUE TITLE
@context vs @type

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipld#5]
@jbenet quick question that was left unanswered during the meeting:

@context can make our JSON blobs look nicer, but it also means that other people would have to use our context or create their own while importing the @type's from our @context, since there can be only one context per JSON blob.

What would be the best way for people to merge our @context into their @context?

//cc @whyrusleeping

**Comment by mildred** [comment]
@context can be an array linking to multiple contexts. Each is applied in the order given and this results in a merged context.

See: http://www.w3.org/TR/json-ld/#advanced-context-usage

You can also specify the @context into sub parts of the JSON tree, not necessarily at the root node.

**Comment by daviddias** [comment]
Thank you for clarifying that @mildred :)
